version: "3.9"
services:
  beat-web-stub:
    environment: 
      PORT: 8080
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: beat-web-stub.Dockerfile
    networks: 
      - integration-test-network
  integration-tests:
    build:
      context: ./
      dockerfile: integration-test.Dockerfile
    environment: 
      BEAT_URL: http://beat-web-stub:8080
    networks: 
      - integration-test-network
    depends_on: 
      - beat-web-stub
  geocode-stub:
    environment: 
      PORT: 8081
    ports:
      - 8081:8081
    build:
      context: ./
      dockerfile: geocode-stub.Dockerfile
    networks: 
      - integration-test-network

networks: 
  integration-test-network:
    
