version: "3.9"
services:
  beat-web-stub:
    environment: 
      PORT: 80
    ports:
      - 8080:80
    build:
      context: ./
      dockerfile: beat-web-stub.Dockerfile
    networks: 
      - integration-test-network
  integration-tests:
    build:
      context: ./
      dockerfile: integration-test.Dockerfile
    environment: 
      GOOGLE_GEOCODE_URL: http://geocode-stub/maps/api/geocode/json
      NOMINATIM_GEOCODE_URL: http://geocode-stub/search
      BEAT_URL: http://beat-web-stub
    networks: 
      - integration-test-network
    depends_on: 
      - beat-web-stub
      - geocode-stub
  geocode-stub:
    environment: 
      PORT: 80
    ports:
      - 8081:80
    build:
      context: ./
      dockerfile: geocode-stub.Dockerfile
    networks: 
      - integration-test-network

networks: 
  integration-test-network:
    
