version: "3.9"
services:
  beat-web-stub:
    environment: 
      PORT: 8080
    ports:
      - 8080:8080
    build: integration-test/beat-web-stub
    networks: 
      - integration-test-network
  integration-tests:
    build:
      context: ./
      dockerfile: integration-test.Dockerfile
    environment: 
      BEAT_URL: http://beat-web-stub:8080
    networks: 
      - integration-test-network
    depends_on: 
      - beat-web-stub

networks: 
  integration-test-network:
    
