name: Fetch today's events

on:
  schedule:
    - cron:  '10 14 * * *'

jobs:
  fetch-events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pull image
        run: |
          docker pull ghcr.io/aringeri/gig-guide/scrape-events:latest
      - uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/aringeri/gig-guide/scrape-events:latest
          options: -v ${{ github.workspace }}/data/:/app/data/ -v ${{ github.workspace}}/docs/search:/app/out
          run: |
            mon=$(TZ='Australia/Melbourne' date -I -d "last Monday")
            for i in {0..6}
            do
              dateI=$(TZ='Australia/Melbourne' date -I -d "$mon + $i day")
              day=$(TZ='Australia/Melbourne' date -d $dateI +%a)
              
              mkdir -p /app/out/$day
              /app/scrape-events -i /app/data/geocoded-venues.json \
                  -d $dateI \
                  -o /app/out/$day/FeatureCollection.json 
            done
            
      - run: |
          cat docs/search/FeatureCollection.json
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: docs/search/