name: Fetch today's events

on:
  push:
    branches: [ master ]
  # schedule:
    # - cron:  '55 4 * * *'

jobs:
  fetch-events:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pull image
        run: |
          docker pull ghcr.io/aringeri/gig-guide/scrape-events:latest
      - uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/aringeri/gig-guide/scrape-events:latest
          options: -v ${{ github.workspace }}/data/:/app/data/ -v ${{ github.workspace}}/docs/search:/app/out
          run: |
            /app/scrape-events -d 2023-12-07 -o /app/out/FeatureCollection.json -i /app/data/geocoded-venues.json
      - run: |
          cat docs/search/FeatureCollection.json
      - uses: stefanzweifel/git-auto-commit-action@v5