name: Fetch today's events

on:
  schedule:
    - cron:  '10 14 * * *'

jobs:
  fetch-events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pull image
        run: |
          docker pull ghcr.io/aringeri/gig-guide/scrape-events:latest
      - uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/aringeri/gig-guide/scrape-events:latest
          options: -v ${{ github.workspace }}/data/:/app/data/ -v ${{ github.workspace}}/docs/search:/app/out
          run: |
            todayMel=$(TZ='Australia/Melbourne' date -I)
            /app/scrape-events -d $todayMel -o /app/out/FeatureCollection.json -i /app/data/geocoded-venues.json
      - run: |
          cat docs/search/FeatureCollection.json
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: docs/search/