name: Build executable docker images

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - 'data/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
    - name: Docker pull cache image
      run: make pull-cache
    - name: Build library image
      run: |
        make lib -o cache
    - name: Build and push 'scrape-events' image
      run: |
        make scrape-events -o lib
        make push-scrape-events
