name: Build executable docker images

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - 'data/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Docker pull cache image
      run: make pull-cache
    - name: Build library image
      run: |
        make lib -o cache
    - name: Build 'scrape-events' image
      run: |
        make scrape-events -o lib
    - name: Push 'scrape-events' image
      run: |
        make push-scrape-events
