name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        docker build . -f gig-guide-cache.Dockerfile -t aringeri/gig-guide-cache
    - name: Build
      run: |
        docker build . -f gig-guide-lib.Dockerfile -t aringeri/gig-guide-lib
    - name: Test Specs
      run: |
        docker build . -f gig-guide-spec.Dockerfile -t aringeri/gig-guide-spec
        docker run -it aringeri/gig-guide-spec
    - name: Integration test
      run: |
        docker-compose -f integration-test-docker-compose.yml run integration-tests
