name: Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
    - name: Docker pull cache
      run: make pull-cache || true
    - name: Install dependencies
      run: |
        make cache-from-docker-repository
    - name: Upload cache image
      run: |
        make push-cache
    - name: Build
      run: |
        make lib -o cache
    - name: Test Specs
      run: |
        make run-specs -o lib
    - name: Integration test
      run: |
        make run-integration-tests -o integration-test
    - name: Build and push 'scrape-venues' image
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        make scrape-venues GIT_SHA=${GITHUB_SHA} -o lib
        make push-scrape-venues GIT_SHA=${GITHUB_SHA}
