name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
    - name: Docker pull cache
      run: docker pull docker.pkg.github.com/aringeri/gig-guide/gig-guide-cache:latest || true
    - name: Install dependencies
      run: |
        docker build . -f gig-guide-cache.Dockerfile -t aringeri/gig-guide-cache --cache-from=docker.pkg.github.com/aringeri/gig-guide/gig-guide-cache:latest
    - name: Upload cache image
      run: |
        docker tag aringeri/gig-guide-cache docker.pkg.github.com/aringeri/gig-guide/gig-guide-cache:latest
        docker push docker.pkg.github.com/aringeri/gig-guide/gig-guide-cache:latest
    - name: Build
      run: |
        docker build . -f gig-guide-lib.Dockerfile -t aringeri/gig-guide-lib
    - name: Test Specs
      run: |
        docker build . -f gig-guide-spec.Dockerfile -t aringeri/gig-guide-spec
        docker run aringeri/gig-guide-spec
    - name: Integration test
      run: |
        docker-compose -f integration-test-docker-compose.yml run integration-tests
    - name: Build and push 'scrape-venues' image
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        docker build . -f docker/runtime.Dockerfile --build-arg EXECUTABLE=scrape-venues -t docker.pkg.github.com/aringeri/gig-guide/scrape-venues:${GITHUB_SHA}
        docker push docker.pkg.github.com/aringeri/gig-guide/scrape-venues:${GITHUB_SHA}
